# Generated by Django 5.0.6 on 2024-07-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_date', models.DateField()),
                ('registration_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('contact_person', models.CharField(max_length=100)),
                ('departments', models.CharField(max_length=500)),
                ('num_employees', models.IntegerField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
